export const buyProductLocator = {
    megaMenuDrop: "(//li[contains(@class,'nav-item dropdown')])[1]",
    appleButton: "(//a[contains(@class,'nav-link icon-left')])[1]",
    appleTitle: "//h1[text()='Apple']",
    ipodItem: "(//div[@class='carousel-item active'])[1]",
    addCartButton: "(//button[contains(@class,'btn btn-cart')])[1]",
    viewCartButton: "//a[contains(text(),'View Cart')]",
    verifyShoppingCart: "//div[@class='col-md-8']//h4[1]",
    checkoutButton: "//a[contains(text(),'Checkout')]",
    billingAdress: "(//h4[@class='card-title'])[2]",
    firstNamePayment: "#input-payment-firstname",
    lastNamePayment: "#input-payment-lastname",
    emailPayment: "#input-payment-lastname",
    telephonePayment: "#input-payment-telephone",
    passwordPayment: "#input-payment-password",
    confirmPassPayment: "#input-payment-confirm",
    companyPayment: "#input-payment-company",
    adressPayment: "#input-payment-address-1",
    adressPaymentTwo: "#input-payment-address-2",
    cityPayment: "#input-payment-city",
    postCodePayment: "#input-payment-postcode",
    countryPayment: "input-payment-country",
    regionStatePayment: "input-payment-zone",
    saveButton: "#button-save",

};